package com.example.recyclerviewtest.beans;

import com.example.recyclerviewtest.R;

public class Datas {
    public static int[] icons = {
            R.mipmap.pic_1,
            R.mipmap.pic_2,
            R.mipmap.pic_3,
            R.mipmap.pic_4,
            R.mipmap.pic_5,
            R.mipmap.pic_6,
            R.mipmap.pic_7,
            R.mipmap.pic_8,
            R.mipmap.pic_9,
            R.mipmap.pic_10,
            R.mipmap.pic_1,
            R.mipmap.pic_2,
            R.mipmap.pic_3,
            R.mipmap.pic_4,
            R.mipmap.pic_5,
            R.mipmap.pic_6,
            R.mipmap.pic_7,
            R.mipmap.pic_8,
            R.mipmap.pic_9,
            R.mipmap.pic_10,
            R.mipmap.pic_1,
            R.mipmap.pic_2,
            R.mipmap.pic_3,
            R.mipmap.pic_4,
            R.mipmap.pic_5,
            R.mipmap.pic_6,
            R.mipmap.pic_7,
            R.mipmap.pic_8,
            R.mipmap.pic_9,
            R.mipmap.pic_10,
            R.mipmap.pic_1,
            R.mipmap.pic_2,
            R.mipmap.pic_3,
            R.mipmap.pic_4,
            R.mipmap.pic_5,
            R.mipmap.pic_6,
            R.mipmap.pic_7,
            R.mipmap.pic_8,
            R.mipmap.pic_9,
            R.mipmap.pic_10,
    };
}
